### ISSUE TITLE
小米集团运维工程师(实习)面试

### ISSUE THREAD

**Issue by mhwangdex** [mhwangdex/mhwangdex.github.io#17]
## 0. 自我介绍
您好，我是XXX，目前是XX大学XX专业的学生。我对DevOps和云计算领域有浓厚兴趣，自学了Docker、Kubernetes等容器技术，并在学校的项目中使用GitLab CI/CD实现了自动化部署流程。最近我还尝试部署过Stable Diffusion等AI模型。希望能通过这次实习机会将理论知识应用到实际工作中，提升自己的运维能力。

## 1. 你知道哪些docker命令
常用Docker命令包括：
- `docker run`：创建并启动容器
  ```
  docker run -d -p 8080:80 --name mynginx nginx
  ```
- `docker ps`：查看运行中的容器
  ```
  docker ps -a  # 查看所有容器(包括停止的)
  ```
- `docker images`：列出本地镜像
- `docker build`：构建镜像
  ```
  docker build -t myapp:v1 .
  ```
- `docker exec`：进入运行中的容器
  ```
  docker exec -it mynginx bash
  ```
- `docker logs`：查看容器日志
  ```
  docker logs -f mynginx
  ```
- `docker stop/start/restart`：停止/启动/重启容器
- `docker rm`：删除容器
- `docker rmi`：删除镜像
- `docker network`：管理网络
  ```
  docker network create mynet
  ```

## 2. Dockerfile中的常用命令有哪些
Dockerfile常用指令：
- `FROM`：指定基础镜像
  ```
  FROM ubuntu:20.04
  ```
- `RUN`：执行命令
  ```
  RUN apt-get update && apt-get install -y curl
  ```
- `COPY`：复制文件到镜像
  ```
  COPY ./app /app
  ```
- `ADD`：类似COPY但支持URL和解压
- `WORKDIR`：设置工作目录
  ```
  WORKDIR /app
  ```
- `EXPOSE`：声明端口
  ```
  EXPOSE 8080
  ```
- `ENV`：设置环境变量
  ```
  ENV NODE_ENV production
  ```
- `CMD`：容器启动命令
  ```
  CMD ["python", "app.py"]
  ```
- `ENTRYPOINT`：入口点
- `VOLUME`：定义匿名卷
- `ARG`：构建参数
- `LABEL`：添加元数据

## 3. Dockerfile中ADD和COPY命令的区别
主要区别：
1. **功能差异**：
   - `COPY`：仅支持将本地文件复制到镜像中
   - `ADD`：除复制功能外，还支持：
     - 从URL下载文件
     - 自动解压tar归档文件

2. **使用场景**：
   - 推荐优先使用`COPY`，因为行为更明确
   - 仅在需要ADD的特殊功能时使用它

3. **示例对比**：
   ```dockerfile
   # COPY示例
   COPY requirements.txt /app/
   
   # ADD示例(自动解压)
   ADD app.tar.gz /app/
   
   # ADD示例(从URL下载)
   ADD https://example.com/file.txt /tmp/
   ```

## 4. 谈一下k8s架构
Kubernetes架构主要分为控制平面(Control Plane)和工作节点(Node)：

**控制平面组件**：
1. **API Server**：集群的入口，处理所有REST请求
2. **etcd**：分布式键值存储，保存集群状态
3. **Scheduler**：负责将Pod调度到合适的Node
4. **Controller Manager**：运行各种控制器，确保集群状态符合预期

**工作节点组件**：
1. **kubelet**：负责与Control Plane通信，管理Pod
2. **kube-proxy**：维护节点网络规则，实现服务发现和负载均衡
3. **容器运行时**：如Docker/containerd，运行容器

**附加组件**：
- **CNI插件**：负责Pod网络
- **CSI插件**：负责存储
- **CoreDNS**：集群DNS服务

## 5. k8s pod之间如何通信
Kubernetes中Pod间通信主要通过以下机制实现：

1. **同一Pod内容器通信**：
   - 通过`localhost`和共享的网络命名空间直接通信

2. **同一Node上不同Pod通信**：
   - 通过CNI插件创建的虚拟网络设备(如veth pair)
   - 每个Pod分配唯一IP，通过虚拟网桥通信

3. **不同Node上Pod通信**：
   - 通过集群网络方案(如Flannel/Calico)实现跨节点通信
   - 常见实现方式：
     - Overlay网络(VXLAN)
     - BGP路由
     - 主机路由

4. **Service抽象层**：
   - ClusterIP：集群内虚拟IP
   - NodePort：节点端口暴露
   - LoadBalancer：云提供商负载均衡器
   - Ingress：HTTP路由

5. **kube-proxy作用**：
   - 维护iptables/ipvs规则
   - 实现Service的虚拟IP到Pod IP的转换
   - 提供负载均衡能力

## 6. k8s存储（存储类，PV，PVC）
Kubernetes存储体系：

1. **PersistentVolume (PV)**：
   - 集群中的存储资源，由管理员预先配置
   - 示例YAML：
     ```yaml
     apiVersion: v1
     kind: PersistentVolume
     metadata:
       name: pv-vol1
     spec:
       capacity:
         storage: 10Gi
       accessModes:
         - ReadWriteOnce
       persistentVolumeReclaimPolicy: Retain
       storageClassName: slow
       hostPath:
         path: /mnt/data
     ```

2. **PersistentVolumeClaim (PVC)**：
   - 用户对存储的请求，类似于Pod消耗Node资源
   - 示例YAML：
     ```yaml
     apiVersion: v1
     kind: PersistentVolumeClaim
     metadata:
       name: pvc-1
     spec:
       storageClassName: slow
       accessModes:
         - ReadWriteOnce
       resources:
         requests:
           storage: 3Gi
     ```

3. **StorageClass**：
   - 定义不同类型的存储，支持动态卷供应
   - 示例YAML：
     ```yaml
     apiVersion: storage.k8s.io/v1
     kind: StorageClass
     metadata:
       name: fast
     provisioner: kubernetes.io/aws-ebs
     parameters:
       type: gp2
     ```

4. **使用流程**：
   - 管理员创建StorageClass
   - 用户创建PVC请求存储
   - Kubernetes根据StorageClass动态创建PV
   - Pod通过volumeMounts使用PVC

## 7. k8s配置和状态存储在哪
Kubernetes集群的所有配置和状态数据存储在**etcd**中：

1. **etcd特点**：
   - 分布式、一致的键值存储
   - 使用Raft算法保证一致性
   - 数据以键值形式组织，支持watch机制

2. **存储内容**：
   - 所有API对象(Pod、Service、Deployment等)的定义和状态
   - 集群节点信息
   - 认证和授权数据
   - 配置信息

3. **etcd操作**：
   - 通过API Server访问，不建议直接操作
   - 常用etcdctl命令：
     ```
     ETCDCTL_API=3 etcdctl --endpoints=https://127.0.0.1:2379 \
     --cacert=/etc/kubernetes/pki/etcd/ca.crt \
     --cert=/etc/kubernetes/pki/etcd/server.crt \
     --key=/etc/kubernetes/pki/etcd/server.key \
     get / --prefix --keys-only
     ```

4. **备份与恢复**：
   - 定期备份etcd数据至关重要
   - 使用`etcdctl snapshot save`创建快照
   - 使用`etcdctl snapshot restore`恢复

## 8. k8s apiserver的用法
Kubernetes API Server是集群的入口，主要用法：

1. **REST API访问**：
   - 基础URL：`https://<master-ip>:6443`
   - API路径：`/api/v1` (核心API)，`/apis/apps/v1` (扩展API)

2. **常用操作示例**：
   ```bash
   # 获取所有Pod
   curl -k -H "Authorization: Bearer $TOKEN" https://$API_SERVER/api/v1/pods
   
   # 创建Deployment
   kubectl create deployment nginx --image=nginx --dry-run=client -o yaml | \
   curl -X POST -H "Content-Type: application/yaml" \
   -H "Authorization: Bearer $TOKEN" \
   --data-binary @- https://$API_SERVER/apis/apps/v1/namespaces/default/deployments
   ```

3. **kubectl原理**：
   - kubectl本质上是API Server的客户端
   - 转换命令为API请求发送给API Server

4. **实用技巧**：
   - 使用`kubectl proxy`开启本地代理：
     ```
     kubectl proxy --port=8080
     # 然后访问 http://localhost:8080/api/v1/pods
     ```
   - 查看API资源：
     ```
     kubectl api-resources
     kubectl explain pods
     ```

## 9. k8s KUBECONFIG serviceaccount role等认证相关
Kubernetes认证授权体系：

1. **KUBECONFIG文件**：
   - 包含集群、用户和上下文信息
   - 默认位置：`~/.kube/config`
   - 结构示例：
     ```yaml
     apiVersion: v1
     clusters:
     - cluster:
         certificate-authority-data: <CA>
         server: https://api.example.com
       name: my-cluster
     contexts:
     - context:
         cluster: my-cluster
         user: my-user
       name: my-context
     current-context: my-context
     users:
     - name: my-user
       user:
         client-certificate-data: <CERT>
         client-key-data: <KEY>
     ```

2. **ServiceAccount**：
   - Pod中进程的身份标识
   - 自动挂载token到`/var/run/secrets/kubernetes.io/serviceaccount`
   - 创建示例：
     ```yaml
     apiVersion: v1
     kind: ServiceAccount
     metadata:
       name: my-sa
     ```

3. **Role和RoleBinding**：
   - **Role**：定义命名空间内的权限规则
     ```yaml
     apiVersion: rbac.authorization.k8s.io/v1
     kind: Role
     metadata:
       namespace: default
       name: pod-reader
     rules:
     - apiGroups: [""]
       resources: ["pods"]
       verbs: ["get", "watch", "list"]
     ```
   - **RoleBinding**：将角色绑定到主体(用户/ServiceAccount)
     ```yaml
     apiVersion: rbac.authorization.k8s.io/v1
     kind: RoleBinding
     metadata:
       name: read-pods
       namespace: default
     subjects:
     - kind: ServiceAccount
       name: my-sa
     roleRef:
       kind: Role
       name: pod-reader
       apiGroup: rbac.authorization.k8s.io
     ```

4. **ClusterRole/ClusterRoleBinding**：
   - 类似Role/RoleBinding，但作用于整个集群

## 10. Prometheus等监控系统熟不熟悉
Prometheus是流行的开源监控系统：

1. **核心组件**：
   - Prometheus Server：抓取和存储时间序列数据
   - Exporters：暴露指标(如node-exporter)
   - Alertmanager：处理警报
   - Pushgateway：支持短生命周期任务的指标

2. **监控Kubernetes**：
   - 使用kube-state-metrics监控集群状态
